### PR TITLE
order migrations by filename, optional name to migrations

### PR DESCRIPTION
**Pull request by leite**
fix in migration tests ...

### CODE REVIEW

**Comment by leite** [comment]
@ostinelli let it go! don't hold it back anymore

**Comment by ostinelli** [comment]
I'd love to, but I've lost track. There are 3 different issues that address the same thing.
Is this it?

**Comment by leite** [comment]
@ostinelli I know, @istr did a mess in #10 and missed tests at #18, plus mine can run an specific migration

**Comment by istr** [comment]
both leite's and my PR work for me... 😀

**Comment by leite** [comment]
thank @istr, i did not want to be mean.

doing good with your fork, looking forward for your features :D

**Comment by ostinelli** [comment]
Thank you both. Will merge soon.

**Comment by ostinelli** [comment]
merged c17c45190c7805dd59b209593c985c5d203e60ab.

**Pull request closed without merging**
