### PR TITLE
use locals and add badges

### PR DESCRIPTION
**Pull request by leite**
busted 2.x ready to go ...

### CODE REVIEW

**Comment by ostinelli** [comment]
Not really. Tests are broken. Closing in favor of #25. Will add Travis separately.

**Comment by ostinelli** [comment]
Not really sure what happened here. Your comment is related to busted 2.x, but the commit is https://github.com/leite/gin/commit/b1c82e6822220c2bb3825d78f36d19b01e7a4360.

If this is another PR please open a new one and clarify what its intent is. Thank you.

**Comment by leite** [comment]
I guess I forgot to add the rockspec and I did it in #27 

both #27 and this are related and working [travis/leite/gin](https://travis-ci.org/leite/gin).

anyway, I think you should discuss more with us and encourage people to colaborate about changes not pick and choose or close things right away.

**Comment by ostinelli** [comment]
I'm sorry that you feel this way. I've just spent 4 hours reviewing all discussions, cross-PR, and patches, and brought everything in for v0.2.0.

I'm really glad that you have decided to contribute to gin, but often [simple rules](https://github.com/ostinelli/gin#contributing) have not been followed, which makes it harder to find the necessary time to complete.

For instance in this commit:

 * There's no explanation on what it is for, I have to go through code to try and understand.
 * There are multiple changes which should be separated in different commits (for example, you have added Travis here in the README file).
 * You have two PR which address the same thing: #26 and #27, instead of one commit which does it all.

Hope this makes it clear on why I close this specific issue, rather than thinking that I "close things right away".

Best.
r.

**Pull request closed without merging**
